update code to correspond to latest scoringutils version
hubverse-org/hubEvals pull request #33
Opened 2024-07-18 17:00 UTC by nikosbosse

Who would have thought that this would happen so soon :) 

`scoringutils` just got a new update which slightly changes the interface - `as_forecast` is now `as_forecast_quantile` and `as_forecast_point`. This PR updates the corresponding function to work with the most recent `scoringutils` version.

2024-07-18 17:09 UTC, nickreich approved these changes
Looks good to me.

2024-07-18 17:11 UTC, nickreich requested changes
Sorry, i spoke too soon! Can you increment the package version and add something to the NEWS.md?

2024-07-19 15:40 UTC, nikosbosse commented
How should I increment the package version? The current version is `0.0.0.9000` which is a dev version already. And the `News.md` file is empty - so I think it needs a more comprehensive presentation of the package functionality (as there isn't really anything that the current version updates)

2024-07-19 15:53 UTC, nickreich commented
in our experience, we've had issues where minor code changes have caused hard-to-diagnose downstream issues later. Hence my requests.

I think we should increment to `0.0.0.9001`. But I see the point about it being a dev branch though. I just think we should enforce these small things.

And I re-looked at the guidelines and say that NEWS updates are maybe only necesary for user-facing changes. So maybe that change should be seen as not mandatory.

2024-07-19 15:56 UTC, nikosbosse commented
Is `hubEvals` ever meant to be on CRAN? otherwise it might make more sense to have a separate `dev` branch and have `main` be the latest release?

2024-07-19 15:59 UTC, nickreich approved these changes

2024-07-19 16:01 UTC, merged